<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>much_ui_exportimport_button_refresh_1_jobqueue</name>
   <tag></tag>
   <elementGuidId>2faab08d-d4b8-4504-94f9-80762933a259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button/span[text()='Refresh'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1580205193956</value>
   </webElementProperties>
</WebElementEntity>
